# when using the default proxy server port
local_backend: true

backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: public/img
public_folder: img

collections:
  - name: "pages"
    label: "Pages"
    files:
      - label: "Home"
        name: "home"
        file: "content/pages/home.md"
        fields:
          - {
              label: "Landing Image",
              name: "landing_image",
              widget: "image",
              choose_url: false,
            }
          - {
              label: "Landing Caption",
              name: "caption",
              widget: "string",
              required: true,
            }
          - {
              label: "Meta tag description",
              name: "meta",
              widget: "string",
              required: true,
            }
          - { label: "Body", name: "body", widget: "markdown" }
          - label: "Images"
            name: "images"
            widget: list
            add_to_top: true
            fields:
              - {
                  label: "Image",
                  name: "image",
                  widget: "image",
                  choose_url: false,
                }
              - {
                  label: "Caption",
                  name: "caption",
                  widget: "string",
                  required: false,
                }

      - label: "Contact"
        name: "contact"
        file: "content/pages/contact.md"
        fields:
          - { label: "Body", name: "body", widget: "markdown" }
          - {
              label: "Featured Image",
              name: "featured_image",
              widget: "image",
              choose_url: false,
            }
          - {
              label: "Featured Image Caption",
              name: "caption",
              widget: "string",
              required: true,
            }
          - {
              label: "Meta tag description",
              name: "meta",
              widget: "string",
              required: true,
            }

  - name: "projects"
    label: "Projects"
    folder: "content/projects"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - {
          label: "Featured Image",
          name: "featured_image",
          widget: "image",
          choose_url: false,
        }
      - { label: "Caption", name: "caption", widget: "string", required: true }
      - { label: "Body", name: "body", widget: "markdown" }
      - label: "Images"
        name: "images"
        widget: list
        add_to_top: true
        fields:
          - {
              label: "Image",
              name: "image",
              widget: "image",
              choose_url: false,
            }
          - {
              label: "Caption",
              name: "caption",
              widget: "string",
              required: false,
            }
      - label: "Plants"
        name: "plants"
        widget: list
        summary: "{{fields.plant}}"
        collapsed: true
        add_to_top: true
        field:
          {
            label: Plant,
            name: plant,
            widget: relation,
            collection: plants,
            search_fields: ["title"],
            display_fields: ["title"],
            value_field: title,
          }

  - name: "plants"
    label: "Plants"
    folder: "content/plants"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Image", name: "image", widget: "image", choose_url: false }
