# when using the default proxy server port
local_backend: true

backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: public/img
public_folder: img

collections:
  - name: "projects"
    label: "Projects"
    folder: "content/projects"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Featured Image", name: "featured_image", widget: "image" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "plants"
    label: "Plants"
    folder: "content/plants"
    create: true
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Image", name: "image", widget: "image" }

  - name: "pages"
    label: "Pages"
    files:
      - label: "Home"
        name: "home"
        file: "content/pages/home.md"
        fields:
          - { label: "Landing Image", name: "landing_image", widget: "image" }
          - label: "Sections"
            name: "sections"
            widget: list
            fields:
              - { label: "Text", name: "text", widget: "markdown" }
              - { label: "Image", name: "image", widget: "image" }

      - label: "Contact"
        name: "contact"
        file: "content/pages/contact.md"
        fields:
          - { label: "Body", name: "body", widget: "markdown" }
          - { label: "Featured Image", name: "featured_image", widget: "image" }
